import { NextPage } from 'next';
import React from 'react';
import DefaultLayout from '../layouts/default';


const PrivacyPolicy: NextPage<Record<string, never>> = () => {
    return (
        <div className="my-4 text-justify tracking-wide mx-4 sm:mx-8">
            <h1 className="text-center text-xl font-bold">Privacy Policy</h1>
            <p className="font-normal text-lg text-center mb-4 italic"><span >"Your privacy is very important to us.&nbsp;"</span></p>
            <h4 className="mt-4 text-lg font-semibold mb-4">The following are the privacy policy of kaaphal: </h4>
            <p><span className="font-normal">By entering this website we assume you accept this Privacy Policy as a whole. By clicking your consent (e.g. “Continue,” “Login,” or “Sign-up,”) or by using Kaaphal services, you agree to the Privacy Policy of the Kaaphal.</span></p>
            <p><span className="font-normal">Please do not continue to use Kaaphal’s website if you do not accept all of the Privacy Policy stated on this page.</span></p>
            <p><span className="font-normal">It is Kaaphal’s policy to respect your privacy about any information we may collect while operating our website.&nbsp;</span></p>
            <p><span className="font-normal">This Privacy Policy applies to “Users”, “Client”, “You” and “Your”; “Ourselves”, “We”, “Our” and “Us”; “Party”, “Parties”, or “Us”, Their description is defined below.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
            <p><span className="font-normal">“Users”, “Client”, “You” and “Your” refers to you, the person accessing this website, and the people who have made an account on Kaaphal, accepting the Company’s terms and conditions. “The Company ”, “Ourselves”, “We”, “Our” and “Us”, refers to Kaaphal. “Kaaphal services’ ‘ or “services’ ‘ means the information, educational, and articles posted on the Kaaphal sites that Kaaphal offers to the users. “Party”, “Parties”, or “Us”, refers to both the Users and ourselves, or either the Users or ourselves. “Content” means all the things inside www.kaaphal.com. Users’ content means the articles they provide to Kaaphal to post, their images, and personal information.</span></p>
            <p><span className="font-normal">We respect your privacy and are dedicated to protecting personally identifiable information you may provide us through the Website. We have embraced this privacy policy (“Privacy Policy”) to explain what information may be collected on our Website, how we use this information, and under what conditions we may disclose the information to third parties.&nbsp;</span></p>
            <p><span className="font-normal">This Privacy Policy applies only to information/data we obtain through our website. It does not apply to our collection of information/data from other sources.</span></p>
            <p><span className="font-normal">This Privacy Policy, together with the Terms and conditions on our Website, set forth the general rules, regulations, and policies administering your utilization of our Website.&nbsp;</span></p>
            <p><span className="font-normal">Depending on your actions when visiting our Website, you may be asked to agree to further terms and conditions.</span></p>
            <p><span className="font-normal">When you use Kaaphal services, we receive some personal information from you like the type of device you’re using and your IP address.&nbsp;</span></p>
            <p><span className="font-normal">You can choose to share further information with us like your images, email address, bio, interested in, comments, posts, and your social media links if you make your account on the Kaaphal.&nbsp;</span></p>
            <p><span className="font-normal">We use this information for things to keep your account secure.</span></p>
            <p><span className="font-normal">In addition to the information you share with us, we use your posts, comments, content you’ve read, Liked, and other information to determine what topics you’re interested in, your age, your native languages, and other signs to show you more suitable content.&nbsp;</span></p>
            <p><span className="font-normal">If you have questions about this policy, how we collect or process your data, or anything else related to our privacy practices, we want to hear from you. You can contact us at any time.</span></p>
            <h5 className="mt-4 text-lg"><strong>Information You Share With Us</strong></h5>
            <p><strong>Basic Account Information &amp; Privacy</strong></p>
            <p><span className="font-normal">It is not compulsory to make an account to access the Kaaphal. But to access some services it will be compulsory to have your account.</span></p>
            <p><span className="font-normal">You can make your account on Kaaphal. You can log in through your Gmail &amp; Facebook account, or, register through your email address. While doing so, your profile will be public. Your profile photo, first and last name, &amp; email address will be public. If you post articles, &amp; comments on some content you like that will be public too, But other additional information like bio, interested in, social media links will be public only if you add the data.</span></p>
            <p><span className="font-normal">Your articles/contents you send us to post and your comments on other’s articles/contents are always public.</span></p>
            <p><strong>Contact Information</strong></p>
            <p><span className="font-normal">We use your contact information, such as your email address to validate your account and keep it protected, and to help prevent spam, fraud, and abuse.&nbsp;</span></p>
            <p><span className="font-normal">We also use contact information to allow certain account features (for example, for login verification ), and to grant you information about our services, and to personalize our services, including ads. Kaaphal also uses your contact information to market to you as your country’s laws allow, and to help others find your account if your settings permit, including through third-party services and client applications. You can use your settings for email and mobile notifications to control notifications you receive from Kaaphal. You can also unsubscribe from notifications.</span></p>
            <p><span className="font-normal">If you email us, we will keep the content of your message, your email address, and your contact information private and use it to respond to your request.</span></p>
            <h5 className="mt-4 text-lg"><strong>Additional Information We Receive About You</strong></h5>
            <p><strong>Location Information</strong></p>
            <p><span className="font-normal">We may obtain, use, and store additional information about your location – such as your current exact position or places. We need information about your signup and current location, which we receive from signals such as your IP address or device settings, to securely and reliably set up and keep your account and to give our services to you.</span></p>
            <p><strong>Links</strong></p>
            <p><span className="font-normal">Our Service may include links to external sites that are not managed by us. If you click on a third-party link, you will be directed to that third party’s site. We firmly suggest you review the Privacy Policy and the terms and conditions of every site you visit.</span></p>
            <p><span className="font-normal">We have no authority over and assume no accountability for the content, privacy policies, or practices of any third party sites, products, or services.</span></p>
            <p><span className="font-normal">If you click on an external link or ad on our services, that advertiser or website operator might figure out that you came from Kaaphal, along with other information associated with the ad you clicked such as characteristics of the audience it was intended to reach. They may also collect other personal data from you, such as cookie identifiers or your IP address.</span></p>
            <p><strong>Aggregate Statistics</strong></p>
            <p><span className="font-normal">We share or disclose non-personal data, such as aggregated information like the total number of times people engaged with our posts, demographics, the number of people who clicked or liked on a particular link, some assumed interests, or reports to advertisers regarding how many people saw or clicked on their ads.</span></p>
            <h5 className="mt-4 text-lg"><strong>Advertisements</strong></h5>
            <p><span className="font-normal">Advertising revenue allows us to support and improve our services. We use the information described in this Privacy Policy to help secure our advertising more applicable to you, to measure its effectiveness, and to help identify your devices to serve you ads on and off of Kaaphal. Our ad partners and affiliates share information with us such as browser cookie IDs, mobile device IDs, demographic or interest data, and content viewed or actions taken on a website or app. Some of our ad partners, particularly our advertisers, also allow us to collect similar information directly from their website or app by integrating our advertising technology. Information shared by ad partners and affiliates or collected by Kaaphal from the websites and apps of ad partners and affiliates may be combined with the extra information you share with Kaaphal and that Kaaphal receives about you described elsewhere in our Privacy Policy.</span></p>
            <p><span className="font-normal">Besides, our ads policies prohibit advertisers from targeting ads based on categories that we consider sensitive or are prohibited by law, such as race, religion, politics, sex life, or health.&nbsp;</span></p>
            <p><span className="font-normal">If you are an advertiser or a planned advertiser, we process your data to help offer and provide our advertising services.&nbsp;</span></p>
            <p><span className="font-normal">This Privacy Policy covers the usage of cookies by Kaaphal and does not include the use of cookies by any advertisers.</span></p>
            <h5 className="mt-4 text-lg"><strong>Cookies</strong></h5>
            <p><span className="font-normal">A cookie is a little piece of data that is stored on your computer or mobile device, and that the visitor’s browser provides to the website each time the visitor returns. Like many websites, we use cookies and similar technologies to collect additional website usage data and to operate our services. Cookies may not be required for many sections of our services. Although most web browsers automatically acquire cookies, many browsers’ settings can be set to refuse cookies or alert you when a website is attempting to place a cookie on you. Still, some of our services may not function properly if you disable cookies. When your browser or device allows it, we use cookies to better understand how you interact with our services, to display personalized content, appropriate advertising, and store your preferences on your computer.&nbsp;</span></p>
            <p><span className="font-normal">By proceeding to operate our website without changing your cookie settings, you hereby acknowledge and agree to Kaaphal’s use of cookies.</span></p>
            <h5 className="mt-4 text-lg"><strong>Account Deletion</strong></h5>
            <p><span className="font-normal">You can delete your Kaaphal account anytime without any reason whatsoever. Keep in mind that search engines and other third parties may still hold copies of your public information, like your profile information and posts, even after you have deleted the information from our services.</span></p>
            <p><span className="font-normal">If you post hate, malice, or evil comments on our posts or user’s articles in the comment section, we will delete your account immediately. If you post pornographic links, unlawful links, and links which we or other users do not find appropriate and have complaints in the comment section, we will delete your account immediately. You will receive an email regarding those issues.</span></p>
        </div >)
}

PrivacyPolicy.getLayout = (page: JSX.Element): React.ReactNode => <DefaultLayout>{page}</DefaultLayout>
export default PrivacyPolicy;